repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0
    hooks:
      - id: upgrade-type-hints
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ['--line-length=119']
        verbose: true
  # - repo: https://github.com/asottile/add-trailing-comma
  #   rev: v3.0.1
  #   hooks:
  #     - id: add-trailing-comma
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args: ['-r', '-i', '--remove-all-unused-imports', '--remove-unused-variables']
        verbose: true
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
